# Generated by Django 5.1.2 on 2025-01-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tblfooter_tblslides_tblsocialmedia_tblsubtopmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutName', models.CharField(max_length=200, null=True)),
                ('AboutImage', models.ImageField(upload_to='images/')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(max_length=200, null=True)),
                ('ContactImage', models.ImageField(upload_to='images/')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GalleryName', models.CharField(max_length=200, null=True)),
                ('GalleryImage', models.ImageField(upload_to='images/')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200, null=True)),
                ('ProductImage', models.ImageField(upload_to='images/')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=200, null=True)),
                ('ServiceImage', models.ImageField(upload_to='images/')),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tblsubtopmenu',
            name='TopMenuID',
        ),
        migrations.AlterField(
            model_name='tblsocialmedia',
            name='socialMediaImage',
            field=models.ImageField(upload_to='SocialMedia'),
        ),
        migrations.AlterField(
            model_name='tbltopmenu',
            name='topMenuImage',
            field=models.ImageField(upload_to='TopMenu'),
        ),
        migrations.DeleteModel(
            name='tblSub2TopMenu',
        ),
        migrations.DeleteModel(
            name='tblSubTopMenu',
        ),
    ]
