# Generated by Django 5.1.2 on 2025-01-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_about_contact_gallery_product_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblTopMenu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topMenuName', models.CharField(max_length=200, null=True)),
                ('topMenuImage', models.ImageField(upload_to='TopMenu')),
            ],
        ),
    ]
