# Generated by Django 5.1.2 on 2025-02-01 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tbltopmenu2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductPrice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='tblGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryName', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('priceIn', models.CharField(max_length=200, null=True)),
                ('priceOut', models.CharField(max_length=200, null=True)),
                ('instock', models.CharField(max_length=200, null=True)),
                ('productImage', models.ImageField(upload_to='ProductImages/')),
                ('productDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('galleryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
        ),
    ]
